services:

  app_proxy:
    environment:
      APP_HOST: zigbee2mqtt_app_1
      APP_PORT: 8080

  app:
    image: koenkk/zigbee2mqtt:latest-dev@sha256:ae334e4d1701856a313a7a1d77ae16d479227f8b8b65ebf450548d5706bb4883
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data:rw
    user: '1000:1000'
