services:

  app_proxy:
    environment:
      APP_HOST: zigbee2mqtt_app_1
      APP_PORT: 8080

  app:
    image: koenkk/zigbee2mqtt:2.3@sha256:42de8c55dc578a8404a18c43aeb2b7c75be7988179abe9a8195d99a9e7ebb917
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data:rw
    user: '1000:1000'
    environment:
      ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED: "true"
      ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: 8080
      Z2M_ONBOARD_NO_REDIRECT: 1
