services:

  app_proxy:
    environment:
      APP_HOST: zigbee2mqtt_app_1
      APP_PORT: 8080

  app:
    image: koenkk/zigbee2mqtt:2.2@sha256:8a7d164906a69dab48d8f761920c9672ad889e16e27db4b912afee7903b102d7
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/app/data:rw
    user: '1000:1000'
